/**
 * Environment Setup Script
 * 
 * Creates .env.local files for all project components.
 * Run with: node setup-env.js
 */

import { writeFileSync, existsSync } from 'fs';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = __dirname;

const envFiles = {
  'apps/api/.env.local': `# API Environment Variables
# Generated by setup-env.js

# Server Configuration
PORT=3001
NODE_ENV=development

# CORS Configuration
CORS_ORIGIN=http://localhost:3000

# Database (for future implementation)
# DATABASE_URL=postgresql://user:password@localhost:5432/articles_db

# Authentication (for future implementation)
# JWT_SECRET=your-secret-key-here
`,

  'apps/frontend/.env.local': `# Frontend Environment Variables
# Generated by setup-env.js

# API URL - Backend API endpoint
VITE_API_URL=http://localhost:3001
`,

  'scripts/automation/.env.local': `# Automation Script Environment Variables
# Generated by setup-env.js

# Node Environment
NODE_ENV=development

# Request Timeout (milliseconds)
REQUEST_TIMEOUT=30000

# Google Custom Search API (optional - has web scraping fallback)
# Get your API key and Search Engine ID from:
# https://developers.google.com/custom-search/v1/overview
GOOGLE_API_KEY=your-google-api-key-here
GOOGLE_SEARCH_ENGINE_ID=your-search-engine-id-here

# LLM Provider Configuration
# Choose one: OpenAI or Anthropic

# For OpenAI:
OPENAI_API_KEY=your-openai-api-key-here
LLM_PROVIDER=openai

# For Anthropic (uncomment if using Anthropic instead):
# ANTHROPIC_API_KEY=your-anthropic-api-key-here
# LLM_PROVIDER=anthropic

# API URL - Backend API endpoint for storing articles
API_URL=http://localhost:3001

# Note: If Google API credentials are not provided, the service will
# attempt to use web scraping as a fallback (less reliable).
# LLM credentials are required for article improvement features.
`
};

console.log('Setting up environment files...\n');

let created = 0;
let skipped = 0;

for (const [filePath, content] of Object.entries(envFiles)) {
  const fullPath = join(rootDir, filePath);
  
  if (existsSync(fullPath)) {
    console.log(`⏭️  Skipped: ${filePath} (already exists)`);
    skipped++;
  } else {
    try {
      // Ensure directory exists
      const pathParts = filePath.split('/');
      const dirPath = join(rootDir, ...pathParts.slice(0, -1));
      if (!existsSync(dirPath)) {
        // Directory should exist, but just in case
        console.log(`⚠️  Warning: Directory ${dirPath} does not exist`);
      }
      
      writeFileSync(fullPath, content, 'utf8');
      console.log(`✅ Created: ${filePath}`);
      created++;
    } catch (error) {
      console.error(`❌ Error creating ${filePath}:`, error.message);
    }
  }
}

console.log(`\n✨ Setup complete!`);
console.log(`   Created: ${created} file(s)`);
console.log(`   Skipped: ${skipped} file(s) (already exist)`);
console.log(`\n📝 Next steps:`);
console.log(`   1. Edit the .env.local files and add your API keys`);
console.log(`   2. See SETUP_ENV.md for detailed instructions`);

